pipeline {
    agent any

    tools {
        maven 'MAVEN_HOME'
        jdk 'JDK17'
    }

    stages {
        stage('Checkout') {
            steps {
                echo '📦 Cloning GitHub repository...'
                git branch: 'master', url: 'https://github.com/thanh241203/connect-with-jenkin.git'
            }
        }

        stage('Build') {
            steps {
                echo '🔨 Building the project...'
                bat 'mvn clean package -DskipTests'
            }
        }

        stage('Run') {
            steps {
                echo '🚀 Starting application...'
                bat 'java -jar target/*.jar'
            }
        }
    }

    post {
        success {
            echo '✅ Build & Run successful!'
        }
        failure {
            echo '❌ Build failed!'
        }
    }
}
