pipeline {
    agent any

    environment {
        DOCKERHUB_USER = 'thanhkon241203265'
        DOCKERHUB_PASS = credentials('dockerhub-credentials')  // lưu trên Jenkins
        IMAGE_NAME = 'thanhkon241203265/ks-app'
    }
    tools {
        maven 'MAVEN_HOME'
        jdk 'JDK17'
    }

    stages {
        stage('Checkout') {
            steps {
                echo '📦 Cloning GitHub repository...'
                git branch: 'master', url: 'https://github.com/thanh241203/connect-with-jenkin.git'
            }
        }

        stage('Build') {
            steps {
                echo '🔨 Building the project...'
                dir('demo'){
                    bat 'mvn clean package -DskipTests'
                }
            }
        }

        stage('Build Docker Image') {
            steps {
                script {
                    def imageTag = "v${env.BUILD_NUMBER}"
                    sh "docker build -t ${IMAGE_NAME}:${imageTag} ."
                    sh "docker tag ${IMAGE_NAME}:${imageTag} ${IMAGE_NAME}:latest"
                }
            }
        }

        stage('Push Docker Image') {
            steps {
                script {
                    sh "echo ${DOCKERHUB_PASS} | docker login -u ${DOCKERHUB_USER} --password-stdin"
                    def imageTag = "v${env.BUILD_NUMBER}"
                    sh "docker push ${IMAGE_NAME}:${imageTag}"
                    sh "docker push ${IMAGE_NAME}:latest"
                }
            }
        }

        stage('Deploy to Kubernetes') {
            steps {
                script {
                    sh '''
                    kubectl set image deployment/demo-deploy demo-container=${IMAGE_NAME}:latest --record
                    kubectl rollout status deployment/demo-deploy
                    '''
                }
            }
        }

        stage('Run Docker Container') {
            steps {
                bat '''
                docker stop demo-app || true
                docker rm demo-app || true
                docker run -d -p 8080:8080 --name demo-app demo-app:latest
                '''
            }
        }
    }

    post {
        success {
            echo '✅ Build & Run successful!'
        }
        failure {
            echo '❌ Build failed!'
        }
    }
}
